version: "3"
services:
  app:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Map the /src folder into the /app/src inside the docker container
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"